import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { fontPoppins } from "@/fonts";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Restaurant",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"bg-background font-sans antialiased",
					fontPoppins.variable
				)}
			>
				<ConvexClientProvider>{children}</ConvexClientProvider>
			</body>
		</html>
	);
}
