import "./globals.css";

import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { fontPoppins } from "@/fonts";
import NextTopLoader from "nextjs-toploader";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Restaurant",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"bg-background font-sans antialiased",
					fontPoppins.variable
				)}
			>
				<ConvexClientProvider>
					<NextTopLoader
						height={6}
						showSpinner={false}
						color="#F66B15CC"
					/>
					<Toaster />
					{children}
				</ConvexClientProvider>
			</body>
		</html>
	);
}
